name: Pull Request Merge Precondition

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose --exclude migrations"

      - uses: isort/isort-action@master
        with:
          configuration: "--check-only --diff --profile black"
          requirementsFiles: "requirements.txt"
